### ISSUE TITLE
no z axis output

### ISSUE THREAD

**Issue by cuca94** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#1]
Hi again!

I am using your code with an AWR1642 board on SDK3.3.
Running fine so far, but im not getting any output on the z axis. I thought the board isn't capable of calculating the z data, but now i read the obstacle detection example where they use the 1642 for 3D output. There they use the special AWR1642 "ODS" Board which is able to get elevation.

is there a way to get z axis (elevation) data with the normal 1642 Boost board?

Link to the obstacle detection guide:
http://dev.ti.com/tirex/content/mmwave_automotive_toolbox_2_7_1/labs/lab0004_obstacle_detection/docs/ODSdemo_usersguide.html

**Comment by ibaiGorordo** [comment]
Hi,

I guess you were using the configuration I uploaded to this repository. I forgot to set it to 3D, so it was only using the 2 horizontal transmitter antennas, that is why there was no Z data. I have updated the configuration file to use the 3 transmitter antennas so it should work now. 

However, I do not have the board here, so I am not sure if I edited the configuration correctly. If it gives you some error, go to the demo visualizer from TI and generate a proper configuration file.

Hope it fixes your problem,
Ibai

**Comment by cuca94** [comment]
I think your edit is only for the AWR1843 because und the AWR1642 has just 2 Tx antennas...

**Comment by ibaiGorordo** [comment]
Yeah, sorry. I forgot that you were using the AWR1642BOOST board. With the normal  AWR1642BOOST board it is impposible to get 3D data because the antennas are in the same horizontal level. You need to have some of the antennas at different heights (like in the AWR1642 "ODS" board) to get 3D position.

**Comment by cuca94** [comment]
yeah, that's what i thought..thank you
