### ISSUE TITLE
C++ implemention

### ISSUE THREAD

**Issue by anathema43** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#12]
hi, is there a c++ implementation of this code?

**Comment by ibaiGorordo** [comment]
Hi,

I have not tried it, if you find a good serial port library, it should not be that difficult to port the code. However, if you are going to use it in ROS, you can check this other repository:

https://github.com/radar-lab/ti_mmwave_rospkg
