### ISSUE TITLE
Collecting data from Sensor AWR1642

### ISSUE THREAD

**Issue by RanjaniN-10** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#13]
Hi,
I'm using your python code for collecting data like range, velocity from AWR1642 Radar. I have replaced the config file of the python code with config from the mmwave demo visualizer. 

I could visualize the range in DemoVisualizer (refer image) 

![Demovisualizer](https://user-images.githubusercontent.com/60179845/110280783-6b647380-8001-11eb-9e55-12d16392687d.png)

I am  able to get the velocity using your code, but not the range(in meters).

![velocity](https://user-images.githubusercontent.com/60179845/110280790-70c1be00-8001-11eb-87e1-d442220be1f0.png)
Could you please help me with finding the range?

System Configuration:
OS type: Ubuntu 18.04, 64bit
Processor: Intel Core i7-7700 CPU @ 3.60GHz × 8
RAM: 16GB
GPU: GeForce GTX 1080 Ti

Thanks in advance
Ranjani N

**Comment by ibaiGorordo** [comment]
Hi, are you interested on the range profile like in the demo visualizer, or are you looking to get the range of the detected points?

**Comment by RanjaniN-10** [comment]
Hi, 
Thanks for your reply. We need to know the range of the detected point in meters.

**Comment by ibaiGorordo** [comment]
In thay case it should be easy, you just need to do sqrt(x^2+y^2+z^2).

I am writing with the phone so I can't give you the exact code, but you should be able to easily calculate it using numpy.

**Comment by RanjaniN-10** [comment]
Hi @ibaiGorordo 

Thanks for the reply, found the equation for calculating range and successfully implemented using numpy library.

**Comment by ibaiGorordo** [comment]
Glad to hear that.

Just for future reference I am writing the code here:

`range = np.sqrt(detObj["x"] ** 2 + detObj["y"] ** 2 + detObj["z"] ** 2) `

(it could be possible to use the numpy norm function by combining the arrays into a 2D array)

closing thread.
