### ISSUE TITLE
Raspberry pi 4, OS compatiblity for mmWave Sensor SDK 3.5

### ISSUE THREAD

**Issue by Malathi15** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#14]
Hi @ibaiGorordo 
I am trying to use Raspberry pi 4 for AWR1642 Radar. Can you please tell me if Ubuntu 18.04LTS is compatible with the Raspberry Pi 4? If not can you please let me know the compatible OS(Raspbian/ Ubuntu) version that can be used for mmWave SDK in Raspberry Pi 4.

Thanks in Advance
Malathi K

**Comment by ibaiGorordo** [comment]
I tested it on Raspbian.

However, this repository only writes and reads to the serial port, parses the raw output of the radar and plots the data, so it should work in any OS where you can install python and the required libraries.

**Comment by Malathi15** [comment]
@ibaiGorordo Thank you for your reply
