### ISSUE TITLE
Increasing Range, Finding Free space grid and Clustering 

### ISSUE THREAD

**Issue by Malathi15** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#15]
Hi @ibaiGorordo 

I am using AWR1642BOOST. Demo visualizer shows the scatter plot of objects detected for about 10 meters and in configuration tab, Maximum Unambiguous Range (meters) also has max value of 10.8 only.

I used the config file from the DemoVisualizer to run your python Code readData_AWR1843.py 
Can I manually extend the range to 40m in the config? If so how to do that?

In this [video](https://www.youtube.com/watch?v=tqKijIRzasg) I see a free space grid and clustering.
How to implement the same in the python code?

Thanks in advance
Malathi K

**Comment by ibaiGorordo** [comment]
You should probably ask this question in the Texas Instruments forum (there might already exist a solution for it) because they can probably help you better.

In my case I focus on very close range measurements (less than 1m) so I have not much experience on modyfing the chirp configuration for long range.

Try to see if you can get the correct confug values using the chirp configuration demo (I forgot the name) or checking the document about the chirp configurations:
https://www.ti.com/lit/pdf/swra553&ved=2ahUKEwjI9dy9hqfvAhXPBKYKHaU8BnwQFjAAegQIAxAD&usg=AOvVaw3LduJ-lo2wvmc9dlGWSTmw


For the clustering you will have to implement it yourself. You can test some DBSCAN python library, it should be straightforward to implement.

**Comment by Malathi15** [comment]
Hi @ibaiGorordo 
Thank you for your reply.

I have tried to calculate the time delay between detection of object by sensor and reading of the data by python code. 
I have printed the time delay in two places separately in your python code (readData_AWR1843.py).

First I have start the time process above the each object data reading
```
                t1_start = process_time()
                for objectNum in range(numDetectedObj):
                    
                    # Read the data for each object
                    x[objectNum] = byteBuffer[idX:idX + 4].view(dtype=np.float32)
                    idX += 4
                    y[objectNum] = byteBuffer[idX:idX + 4].view(dtype=np.float32)
                    idX += 4
                    z[objectNum] = byteBuffer[idX:idX + 4].view(dtype=np.float32)
                    idX += 4
                    point1 = np.array((0, 0, 0)) 
                    point2 = np.array((x[objectNum], y[objectNum], z[objectNum]))
                    dist = np.linalg.norm(point1 - point2)
                    velocity[objectNum] = byteBuffer[idX:idX + 4].view(dtype=np.float32)
                    print("Velocity[", objectNum,"]: ",velocity[objectNum])
                    print("Distance[", objectNum,"]:  ",dist)
                    idX += 4
                t1_stop = process_time()
                print("Elapsed time in seconds:",t1_stop - t1_start)
```
I got the output time delay (like 0.0004 sec) as shown in the picture
![Screenshot from 2021-03-16 12-09-12](https://user-images.githubusercontent.com/46995564/111278361-73ef2680-865f-11eb-811f-27ee0dc0c858.png)

I have also tried to calculate time delay in main function
```
t1_start = process_time()
 Configurate the serial port
CLIport, Dataport = serialConfig(configFileName)

 Get the configuration parameters from the configuration file
configParameters = parseConfigFile(configFileName)

 START QtAPPfor the plot
app = QtGui.QApplication([])

 Set the plot 
pg.setConfigOption('background','w')
win = pg.GraphicsWindow(title="2D scatter plot")
p = win.addPlot()
p.setXRange(-10.0,10.0)
p.setYRange(0,20)
p.setLabel('left',text = 'Y position (m)')
p.setLabel('bottom', text= 'X position (m)')
s = p.plot([],[],pen=None,symbol='o')
    
   
 Main loop 
detObj = {}  
frameData = {}    
currentIndex = 0
while True:
    try:
        # Update the data and check if the data is okay
        dataOk = update()
        
        if dataOk:
            # Store the current frame into frameData
            frameData[currentIndex] = detObj
            currentIndex += 1
        
        time.sleep(0.05) # Sampling frequency of 30 Hz
        t1_stop = process_time()
        print("Elapsed time in seconds:", t1_stop - t1_start)
```
when calculate the time delay in main function I got an output like 2.7 sec. Please check the screenshot
![Screenshot from 2021-03-16 14-05-57](https://user-images.githubusercontent.com/46995564/111279703-f75d4780-8660-11eb-85fc-81df589f3845.png)

I am confused with this two different time delay values. I need to know the exact time delay between detection and printing of velocity, range and 2D plot.

Can you please help me with this issue.

**Comment by ibaiGorordo** [comment]
Hi, the second delay is probably correct because it also takes into account the delay in the calculations before the for loop you measured in your first time measurement.

However, what is inside your process_time() function? I think there is something wrong because you have a time.sleep(0.05) in the middle and the elapsed time is less than that value.

**Comment by Malathi15** [comment]
Thank you for your reply @ibaiGorordo 

The process_time() is a pre-defined function. `time.process_time()` function always returns the float value of time in seconds. Return the value (in fractional seconds) of the sum of the system and user CPU time of the current process. It does not include time elapsed during sleep.

**Comment by ibaiGorordo** [comment]
I see, I didn't know that, good to know! As I mentioned, the second value is probably the correct one.

Just curious, what do you want to know the elapsed time?

**Comment by Malathi15** [comment]
Thank you for your reply @ibaiGorordo 
I am testing the response time of a python code when connected to `AWR1642`
