### ISSUE TITLE
Labelling Scatter Plot Point 

### ISSUE THREAD

**Issue by Malathi15** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#17]
Hi,
I am using AWR1642 for detecting objects. While using your code, Qt GUI has scatter plot which shows the real time data and plots it. I am curious about can we number the detected objects like first detected object as 1 in plot and second detected object as 2 in plot. If so can you please help me with this ?

Thanks in advance
Malathi K

**Comment by ibaiGorordo** [comment]
Are you asking about just labelling the plot or is it more about each object haing an unique label and keeping it over time (i.e. tracking object)? 

For the first one, I have not much experience with pyqtgraph, so I am not sure what is the best way. A quick search land me to this function (https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/textitem.html), but again, I am not sure how easy or fast will be.

If you also want tracking, then you will have to do clustering and then use some Kalman filter to track the object like in the person detection demo.
