### ISSUE TITLE
Velocity and Detection Regarding

### ISSUE THREAD

**Issue by RanjaniN-10** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#20]
Hi,
I am using AWR1642 EVM to detect objects and your python code to obtain Range, Velocity, Angle. I have fixed EVM in left side of car's dashboard. I could see EVM was not able to sense the right side objects most of the time.

During sensing I have noted that 
1.  Velocity of opposite vehicles as either positive or negative but it has to be negative
2. What is the unit of velocity here?

Could you help me with these queries?

Thanks in advance
Ranjani N

**Comment by ibaiGorordo** [comment]
Hi, 

To be honest I normally do not use much the velocity in my research so I am not sure if the values for the velocity are correct. 

But I have confirmed with the source code of the demo visualizer and it does the same processing to obtain the velocity in m/s.

This is the comments from the source code of the demo visualizer:
```
 /* list of detected objs
    typedef struct DPIF_PointCloudCartesian_t
    {
        x - coordinate in meters
        float  x;
        y - coordinate in meters
        float  y;
        z - coordinate in meters
        float  z;        
        Doppler in m/s 
        float    doppler;
    }DPIF_PointCloudCartesian;
    */
```

Maybe you can try to use the demo visualizer and see if you get similar results.
