### ISSUE TITLE
Visualizing Range Doppler Heatmap (range-dopplerHeatmap_SDK3.py)

### ISSUE THREAD

**Issue by Kwasjd** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#25]
Hi, 

I am currently exploring your python code in visualizing the heatmap. However, the code does not open the heatmap visualization and I noticed the code for creating the heatmap is shown:

                plt.clf()
                cs = plt.contourf(rangeArray,dopplerArray,rangeDoppler)
                fig.colorbar(cs, shrink=0.9)
                fig.canvas.draw()
                plt.pause(0.1)

Is there a way to display the heatmap? 

Thanks

**Comment by Kwasjd** [comment]
Hi, 

Sorry, I managed to display out the heatmap. it turns out the parameters of the guiMonitor in the profile config file seems to prevent the code to display the heatmap visualization. 

Thank you

**Comment by jvithub** [comment]
> Hi,
> 
> Sorry, I managed to display out the heatmap. it turns out the parameters of the guiMonitor in the profile config file seems to prevent the code to display the heatmap visualization.
> 
> Thank you

Hi Kwasjd,
Can I ask how you changed the parameters to display the heatmap? I'm using awr1642 and mine is not showing "guiMonitor -1 1 1 0 0 0 1"
