### ISSUE TITLE
CAN Connectors in AWR1843BOOST EVM

### ISSUE THREAD

**Issue by guruvishnuvardan** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#29]
Hi Ibai,

Good Day!

Can you please let me know the uses of CAN Connectors in AWR1843BOOST EVM? I saw in the TI documentation that using Peak System connector(CAN - USB), we can connect the system to AWR1843 CAN FD.

But, Can you please let me know, how to directly connect the radar to CAN bus in a vehicle? Is it using OBD2 connectors?? 
![Screenshot_20211207-195633~2](https://user-images.githubusercontent.com/31349523/145047683-59de842f-ee46-4d41-a229-b0b85f2cdcfa.png)

Can you please enlighten me, as I am confused about the CAN BUS - AWR1843BOOST Connections

Thanks
Guru

**Comment by ibaiGorordo** [comment]
I have no idea, I have never used the CAN connectors in the device. Ask in the Texas Instruments forums because they will be able to provide you better info.
