### ISSUE TITLE
BIN File

### ISSUE THREAD

**Issue by mosob91** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#3]
Do you have the BIN file to program the AWR1843BOOT EVM? what's the .CFG file?

**Comment by ibaiGorordo** [comment]
Sorry, I have just realized of your comment. 

Probably you already found it, but the bin file can be found in the mmWave SDK.

Regarding .cfg file, you can create your own file using the mmWave Demo Visualizer.

Ibai
