### ISSUE TITLE
AWR1843 VELOCITY CALCULATION

### ISSUE THREAD

**Issue by guruvishnuvardan** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#36]
Hi Ibai,

Good Day!

It's been a while, I hope you are doing fantastic!

Can you please let me, if there is any way we can calculate the real velocity from AWR1843BOOST Radar? , I just wanted to differentiate static and moving obstacles and false positives(noises that confuses me, by looking like real data).

Thanks
Guru

**Comment by ibaiGorordo** [comment]
You can get the velocity using detObj["velocity"]. However, if you want to remove static noise, it might be better in the config file to enable clutter removal in the demo visualizer (https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.6.0/)
![Screenshot from 2022-08-25 08-09-02](https://user-images.githubusercontent.com/43162939/186539997-deee9039-1b08-486e-b0cd-f0b4d48fa739.png)

**Comment by guruvishnuvardan** [comment]
Hi @ibaiGorordo ,

Thanks for your response.

Please find the screenshot of the velocity printed using detObj["velocity"] variable, the data received for velocity of the obstacle in the front is -0.491, is it meter / second? ,  But if I convert it's 1.44 Kilometres / Hour

Can you please let me know, if it's the right conversation method?

![Screenshot_20220825-193428~2](https://user-images.githubusercontent.com/31349523/186688846-a0bccbee-98b0-4009-b2de-efcdb3540fc8.png)



Thanks
Guru

**Comment by ibaiGorordo** [comment]
I don't remember properly, so I am not 100% sure, but I think it is in m/s.

However, it is radial velocity and in your case, since the radar in the car is moving is going to be relative velocity (the difference in velocity between the truck and the car with the radar). Similarly, since your car is moving, even static objects are going to have non 0 velocity.

**Comment by guruvishnuvardan** [comment]
Thanks @ibaiGorordo , Now I understand that the static obstacles won't have velocity zero.

Can you please let me know, if there is any formula to convert the relative velocity that we obtain from AWR1843 to Kilometres Per Hour

**Comment by ibaiGorordo** [comment]
The way you did is fine and to get the absolute velocity you will have to add the car's velocity

**Comment by guruvishnuvardan** [comment]
Thanks @ibaiGorordo
