### ISSUE TITLE
WORKING WITH AWR1243 OR AWR2243

### ISSUE THREAD

**Issue by guruvishnuvardan** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#37]
Hi @ibaiGorordo,

Good Day!

Can you please let me know, if it's possible to extract data from AWR1243BOOST OR AWR2243BOOST IMAGING RADARS? , Using this Code, by changing the Config file.

Thanks
Guru

**Comment by ibaiGorordo** [comment]
For the AWR1243BOOST, probably yes, if it runs the SDK version 3.

For AWR2243BOOST, I have no idea what SDK comes with (some of the second generation 2XXX, come with SDK 4), so I have no idea.

**Comment by guruvishnuvardan** [comment]
Thanks @ibaiGorordo
