### ISSUE TITLE
Blank window when Running readData_AWR1843.py

### ISSUE THREAD

**Issue by YiShan8787** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#4]
I have a this problem when I running the script.

![image](https://user-images.githubusercontent.com/43614278/77427748-df6a3380-6e11-11ea-8c29-cc43b71d5b27.png)

Is my setting wrong?

**Comment by YiShan8787** [comment]
Ahh.....

I solved it by using uniflash to erase the flash and load the demo

then the program can work

thanks for your program

![image](https://user-images.githubusercontent.com/43614278/77430502-44278d00-6e16-11ea-8eb4-5feaafd4f1cc.png)

**Comment by ibaiGorordo** [comment]
I am not sure what might have happened, but I am glad to hear you solved it.

Let me know if you have any other comment/problem.

Ibai
