### ISSUE TITLE
Firmware for AWR1843 (MSS/RSS parts)

### ISSUE THREAD

**Issue by x893** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#40]
Hello,
thanks for your project.
What's firmware need write to AWR1843 flash for mss and rss parts ?
Thanks in advance

**Comment by ibaiGorordo** [comment]
It's been a while, so I don't remind it well, but for the SDK 3, I think you only need to flash one file. However, better check the Texas Instruments documentation.
